# -*- coding: utf-8 -*-
"""E-commerce Sales Trend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRLDmcF86W2K0nRhGHZ6FVudaPKdr_v-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv("/content/ecommerce_realworld_dataset.csv")

# -----------------------------
# 1. DATA CLEANING
# -----------------------------
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Total_Sales_INR'] = df['Quantity'] * df['Unit_Price_INR']
df.dropna(inplace=True)

# Normalize text columns
text_cols = ['Product_Category', 'Product_Name', 'Payment_Method', 'State']
for col in text_cols:
    df[col] = df[col].str.strip().str.title()

# -----------------------------
# 2. KPI CALCULATIONS
# -----------------------------
total_sales = df['Total_Sales_INR'].sum()
avg_order_value = df['Total_Sales_INR'].mean()
total_orders = df['Order_ID'].nunique()
unique_customers = df['Customer_ID'].nunique()

print("Total Sales:", total_sales)
print("Avg Order Value:", avg_order_value)
print("Total Orders:", total_orders)
print("Unique Customers:", unique_customers)

# -----------------------------
# 3. EDA (PLOTS)
# -----------------------------
plt.figure(figsize=(10,5))
sns.lineplot(df.groupby('Date')['Total_Sales_INR'].sum())
plt.title("Daily Sales Trend")
plt.show()

plt.figure(figsize=(10,5))
df.groupby('Product_Category')['Total_Sales_INR'].sum().sort_values().plot(kind='bar')
plt.title("Category-wise Revenue")
plt.show()

plt.figure(figsize=(10,5))
df['Payment_Method'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Payment Method Share")
plt.show()

# -----------------------------
# 4. ML MODEL (SALES PREDICTION)
# -----------------------------
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df['Month'] = df['Date'].dt.month

X = df[['Quantity', 'Unit_Price_INR', 'Month']]
y = df['Total_Sales_INR']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model Score:", model.score(X_test, y_test))

# Export cleaned data for Power BI
df.to_csv("cleaned_sales_data.csv", index=False)
print("Clean dataset exported successfully!")



































